[package]
name = "rast"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.34.1", features = ["rayon"] }
rayon = "1.11.0"

[dev-dependencies]
bmp = "0.5.0"
rand = "0.9.2"
softbuffer = "0.4.6"
winit = "0.30.12"
